server:
    port: 9000
    servlet:
        context-path: /

spring:
    application:
        name: wbkdng-gateway

eureka:
    client:
        serviceUrl:
            defaultZone: http://localhost:9001/eureka

management: 
  endpoints: 
    web: 
      exposure: 
        include: info, health, routes

info:
    app:
        name: ${spring.application.name}
        version: "1.0.0"